/**
 * OpenCode: an npm plugin module. Its `config` hook adds the bundled skills
 * directory to `skills.paths` and the remote MCP server to `mcp`, leaving a
 * user's own `archdev` server entry in place. No session hooks ship until the
 * CLI handles OpenCode's plugin events.
 */
import { harnessHooks } from "../catalog.ts";
import {
  jsonFile,
  skillFiles,
  textFile,
  type GeneratedFile,
} from "../files.ts";
import type { Context } from "./index.ts";

export const root = "plugins/opencode";
export const packageName = "@archastro/archdev-opencode";

export function build({ repoRoot, catalog }: Context): GeneratedFile[] {
  if (harnessHooks(catalog, "opencode"))
    throw new Error("opencode hooks are not implemented in the generator");
  const server = { type: "remote", url: catalog.mcp.url, enabled: true };
  const source = `// Generated by tools/plugin-gen from catalog/archdev.json. Do not edit.
import { fileURLToPath } from "node:url";

const SKILLS = fileURLToPath(new URL("./skills", import.meta.url));

export const ArchDevPlugin = async () => ({
  async config(config) {
    config.skills ??= {};
    const paths = config.skills.paths ?? [];
    if (!paths.includes(SKILLS)) config.skills.paths = [...paths, SKILLS];
    config.mcp ??= {};
    config.mcp[${JSON.stringify(catalog.mcp.name)}] ??= ${JSON.stringify(server)};
  },
});
`;
  return [
    jsonFile(`${root}/package.json`, {
      name: packageName,
      version: catalog.version,
      description: catalog.description,
      type: "module",
      main: "./index.js",
      exports: { ".": "./index.js" },
      files: ["index.js", "skills"],
      keywords: [...catalog.keywords, "opencode", "opencode-plugin"],
      homepage: catalog.homepage,
      repository: { type: "git", url: `git+${catalog.repository}.git` },
      license: catalog.license,
      publishConfig: { access: "public" },
    }),
    textFile(`${root}/index.js`, source),
    ...skillFiles(repoRoot, catalog, `${root}/skills`),
  ];
}
