/**
 * Pi: a Pi package (`package.json` with a `pi` key) holding the skills and an
 * extension that forwards Pi's events to `archdev repo hook`. Pi has no MCP
 * client, so no server ships. The extension mirrors the one
 * `archdev repo hook setup` writes, so a session reports the same way through
 * either install path.
 */
import { harnessHooks, hookTimeout, type Catalog, type HarnessHooks } from "../catalog.ts";
import {
  jsonFile,
  skillFiles,
  textFile,
  type GeneratedFile,
} from "../files.ts";
import type { Context } from "./index.ts";

export const root = "plugins/pi";
export const packageName = "@archastro/archdev-pi";

export function manifest(base: string) {
  return {
    extensions: [`${base}/extensions`],
    skills: [`${base}/skills`],
  };
}

export function build({ repoRoot, catalog }: Context): GeneratedFile[] {
  const hooks = harnessHooks(catalog, "pi");
  return [
    jsonFile(`${root}/package.json`, {
      name: packageName,
      version: catalog.version,
      description: catalog.description,
      keywords: [...catalog.keywords, "pi-package"],
      homepage: catalog.homepage,
      repository: { type: "git", url: `git+${catalog.repository}.git` },
      license: catalog.license,
      files: ["extensions", "skills"],
      pi: hooks ? manifest(".") : { skills: ["./skills"] },
    }),
    ...(hooks
      ? [textFile(`${root}/extensions/archdev.js`, extension(catalog, hooks))]
      : []),
    ...skillFiles(repoRoot, catalog, `${root}/skills`),
  ];
}

function extension(catalog: Catalog, hooks: HarnessHooks): string {
  const on = new Set(hooks.events);
  const action = (event: keyof Catalog["hooks"]["events"]) =>
    JSON.stringify(catalog.hooks.events[event].action);
  const timeoutMs = (event: keyof Catalog["hooks"]["events"]) =>
    hookTimeout(catalog, hooks, event) * 1000;
  const [command, ...prefix] = catalog.hooks.command.split(" ");
  const handlers: string[] = [];
  if (on.has("sessionStart"))
    handlers.push(`  pi.on("session_start", async (_event, ctx) => {
    const current = context(ctx);
    sessionId = current.session_id;
    cwd = current.cwd;
    // repo status cannot see a Pi extension from a child process; bind the
    // readiness signal to this session and hook spec instead.
    process.env.ARCHDEV_PI_HOOK_SESSION_ID = sessionId;
    process.env.ARCHDEV_PI_HOOK_SPEC = SPEC;
    pending = Promise.resolve();
    bootstrap = await hook(${action("sessionStart")}, ${timeoutMs("sessionStart")}, current);
  });`);
  if (on.has("promptSubmit") || on.has("sessionStart"))
    handlers.push(`  pi.on("before_agent_start", async (_event, ctx) => {
    if (ctx.sessionManager.getSessionId() !== sessionId) return;
    await pending;
    const reminder = ${on.has("promptSubmit") ? `await hook(${action("promptSubmit")}, ${timeoutMs("promptSubmit")}, context(ctx))` : `""`};
    const text = [bootstrap, reminder].filter(Boolean).join("\\n\\n");
    bootstrap = "";
    if (text) return { message: { customType: "archdev-monitor", content: text, display: false } };
  });`);
  if (on.has("toolUse"))
    handlers.push(`  pi.on("tool_result", async (event, ctx) => {
    if (ctx.sessionManager.getSessionId() !== sessionId || ctx.cwd !== cwd) return;
    if (!TOOLS.test(event.toolName)) return;
    const payload = { ...context(ctx), toolName: event.toolName, toolInput: event.input };
    // Pi may finish parallel tools together; serialize the monitor's state updates.
    const result = pending.then(() => hook(${action("toolUse")}, ${timeoutMs("toolUse")}, payload));
    pending = result.then(() => undefined);
    const text = await result;
    if (text) return { content: [...event.content, { type: "text", text: "ArchDev monitor: " + text }] };
  });`);
  if (on.has("stop"))
    handlers.push(`  pi.on("agent_settled", async (_event, ctx) => {
    if (ctx.sessionManager.getSessionId() !== sessionId) return;
    await pending;
    await hook(${action("stop")}, ${timeoutMs("stop")}, context(ctx));
  });`);
  handlers.push(`  pi.on("session_shutdown", async () => {
    await pending;
${on.has("sessionEnd") ? `    if (sessionId && cwd) await hook(${action("sessionEnd")}, ${timeoutMs("sessionEnd")}, { session_id: sessionId, cwd });\n` : ""}    if (process.env.ARCHDEV_PI_HOOK_SESSION_ID === sessionId) {
      delete process.env.ARCHDEV_PI_HOOK_SESSION_ID;
      delete process.env.ARCHDEV_PI_HOOK_SPEC;
    }
  });`);
  return `// Generated by tools/plugin-gen from catalog/archdev.json. Do not edit.
// Reload Pi after installation. ArchDev's CLI owns event detection and posting.
const COMMAND = ${JSON.stringify(command)};
const PREFIX = ${JSON.stringify(prefix)};
const HARNESS = ${JSON.stringify(hooks.harness)};
const SPEC = ${JSON.stringify(String(catalog.hooks.spec))};
const TOOLS = new RegExp(${JSON.stringify(hooks.toolMatcher)});
const MISSING_CLI = ${JSON.stringify(catalog.hooks.missingCliGuidance)};
const START = ${action("sessionStart")};

export default function (pi) {
  let bootstrap = "";
  let sessionId;
  let cwd;
  let pending = Promise.resolve();

  async function hook(action, timeout, payload) {
    try {
      const result = await pi.exec(COMMAND, [...PREFIX, action, "--harness", HARNESS, "--spec", SPEC, "--payload", JSON.stringify(payload)], {
        cwd: payload.cwd,
        timeout,
      });
      if (result.code === 127 && action === START) return MISSING_CLI;
      if (result.code !== 0) return "";
      if (action === START) return result.stdout.trim();
      const output = JSON.parse(result.stdout);
      return output?.hookSpecificOutput?.additionalContext || "";
    } catch (error) {
      if (action === START && (error?.code === "ENOENT" || String(error).includes("ENOENT"))) return MISSING_CLI;
      // Monitoring must never prevent a Pi turn or a tool result.
      return "";
    }
  }

  function context(ctx) {
    return { session_id: ctx.sessionManager.getSessionId(), cwd: ctx.cwd };
  }

${handlers.join("\n\n")}
}
`;
}
