// Generated by tools/plugin-gen from catalog/archdev.json. Do not edit.
import { fileURLToPath } from "node:url";

const SKILLS = fileURLToPath(new URL("./skills", import.meta.url));

export const ArchDevPlugin = async () => ({
  async config(config) {
    config.skills ??= {};
    const paths = config.skills.paths ?? [];
    if (!paths.includes(SKILLS)) config.skills.paths = [...paths, SKILLS];
    config.mcp ??= {};
    config.mcp["archdev"] ??= {"type":"remote","url":"https://archdev.ai/api/v1/mcp","enabled":true};
  },
});
