import { lstatSync, readdirSync, readFileSync, rmSync, mkdirSync, writeFileSync, chmodSync, existsSync } from "node:fs";
import path from "node:path";
import { HARNESSES, type Catalog } from "./catalog.ts";
import { jsonFile, textFile, type GeneratedFile } from "./files.ts";
import { ADAPTERS } from "./harnesses/index.ts";
import { marketplaceFiles } from "./marketplaces.ts";
import * as pi from "./harnesses/pi.ts";
import { installGuide } from "./readme.ts";

/**
 * Every path the generator owns. `build` replaces them wholesale and `check`
 * fails on any file under them that the catalog would not produce.
 */
export const OWNED_PATHS = [
  "plugins",
  ".claude-plugin",
  ".grok-plugin",
  ".github/plugin",
  ".cursor-plugin",
  ".agents/plugins",
  "package.json",
] as const;

export function generate(repoRoot: string, catalog: Catalog): GeneratedFile[] {
  const files = [
    ...HARNESSES.flatMap((harness) =>
      ADAPTERS[harness].build({ repoRoot, catalog }),
    ),
    ...marketplaceFiles(catalog),
    textFile("plugins/README.md", installGuide(catalog)),
    // `pi install git:github.com/ArchAstro/archdev@<tag>` reads the root
    // package.json; it points at the generated Pi package.
    jsonFile("package.json", {
      name: "archdev-plugins",
      version: catalog.version,
      private: true,
      description: "Pi package entry point; generated by tools/plugin-gen.",
      keywords: ["pi-package"],
      license: catalog.license,
      pi: pi.manifest(`./${pi.root}`),
    }),
  ];
  const seen = new Set<string>();
  for (const file of files) {
    if (!OWNED_PATHS.some((owned) => file.path === owned || file.path.startsWith(`${owned}/`)))
      throw new Error(`${file.path} is outside the generator's owned paths`);
    if (seen.has(file.path)) throw new Error(`${file.path} is generated twice`);
    seen.add(file.path);
  }
  return files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}

/** Replaces every owned path with the generated files. */
export function writeFiles(repoRoot: string, files: GeneratedFile[]): void {
  for (const owned of OWNED_PATHS)
    rmSync(path.join(repoRoot, owned), { recursive: true, force: true });
  for (const file of files) {
    const target = path.join(repoRoot, file.path);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, file.content);
    chmodSync(target, file.mode);
  }
}

/** Differences between the owned paths on disk and the generated files. */
export function diffFiles(repoRoot: string, files: GeneratedFile[]): string[] {
  const expected = new Map(files.map((file) => [file.path, file]));
  const actual = new Set(OWNED_PATHS.flatMap((owned) => listFiles(repoRoot, owned)));
  const problems: string[] = [];
  for (const file of files) {
    const target = path.join(repoRoot, file.path);
    if (!actual.has(file.path)) problems.push(`missing: ${file.path}`);
    else if (!readFileSync(target).equals(file.content))
      problems.push(`changed: ${file.path}`);
    else if (process.platform !== "win32" && (lstatSync(target).mode & 0o777) !== file.mode)
      problems.push(`mode: ${file.path} should be ${file.mode.toString(8)}`);
  }
  for (const file of [...actual].sort())
    if (!expected.has(file)) problems.push(`unexpected: ${file}`);
  return problems;
}

function listFiles(repoRoot: string, relative: string): string[] {
  const target = path.join(repoRoot, relative);
  if (!existsSync(target)) return [];
  if (!lstatSync(target).isDirectory()) return [relative];
  return readdirSync(target).flatMap((name) =>
    listFiles(repoRoot, `${relative}/${name}`),
  );
}
