/**
 * Every nudge the bundled script can print, in one place. The generator
 * substitutes each `@@name@@` marker in `assets/archdev-nudge.sh.in`, so every
 * harness plugin ships the same words. Text is shell: `$var` is expanded by the
 * script, and `\"` is a literal double quote inside a double-quoted word.
 */
export const NUDGE_TEXT = {
  consent: String.raw`Reporting to the organization stream is covered by the archdev:write consent the user gave when they connected ArchDev: do not ask again, just do it before you reply, and stop only if the user tells you to.`,
  riskSteps: String.raw`read the archdev://risk/definitions/index.json resource and the pinned definition it lists for the type, judge, call archdev_finalize_risk, then pass its sealed and digest to archdev_post_risk_event`,
  start: String.raw`ArchDev is connected through the plugin's MCP server, and nothing reports automatically because the ArchDev CLI is not installed here. Before your first reply: (1) call archdev_get_context (ArchDev MCP); (2) archdev_list_projects and pick the project that covers this work, or archdev_create_project when none fits; (3) archdev_post_activity_event with event \"agent.session_started\" and value {\"session_id\":\"$sid\",\"lifecycle\":\"session_started\",\"harness\":\"claude\"}. Later hook notes name the exact call for each commit, push, plan and pull request, and for each time the user redirects you. $CONSENT The ArchDev CLI is optional: do not install anything or ask about it unless the user brings it up.`,
  firstPrompt: String.raw`ArchDev: call archdev_get_context before your first reply, then report as the session notes say. $CONSENT`,
  steer: String.raw`ArchDev: the user sent another message in this session. Before you reply, call archdev_post_activity_event with event \"agent.steered\", value {\"session_id\":\"$sid\",\"lifecycle\":\"steered\",\"harness\":\"claude\"}, the project_id you chose (archdev_list_projects first if you have none), idempotency_key \"$sid-steered-$seq\". $CONSENT`,
  plan: String.raw`ArchDev: you just wrote the plan file $loc. When you are done editing it this turn, and before you reply, report it once: archdev_post_risk_event with event \"$event\" and value {\"location\":\"$loc\",\"title\":\"<the plan's title>\",\"description\":\"<one or two sentences on what the plan says>\"}, the project_id you chose, an idempotency_key such as \"$sid-$event-<n>\". It needs a sealed risk assessment of the plan: $RISK_STEPS (resource_type \"plan\", subject source archdev:plan:$loc). $CONSENT`,
  commit: String.raw`ArchDev: a git commit just succeeded ($s12). Before you reply, call archdev_post_activity_event with event \"commit.created\", value {\"sha\":\"$h\",\"summary\":\"$subj\"}, the project_id you chose, idempotency_key \"$sid-commit-$s12\". $CONSENT`,
  push: String.raw`ArchDev: a git push just succeeded ($s12). Before you reply, call archdev_post_activity_event with event \"commit.pushed\", value {\"sha\":\"$h\"}, the project_id you chose, idempotency_key \"$sid-push-$s12\".$extra $CONSENT`,
  prCreated: String.raw`ArchDev: you just opened pull request #$pr_n in $pr_repo. Before you reply, report it with archdev_post_risk_event, event \"pr.created\", value {\"repository\":\"$pr_repo\",\"number\":$pr_n,\"summary\":\"<what the PR does>\"}, the project_id you chose, idempotency_key \"$sid-pr-created-$pr_n\". It needs a sealed whole-PR risk assessment: $RISK_STEPS (resource_type \"pr\", subject source archdev:pr:$pr_repo#$pr_n, full 40-character head and base SHAs, which git rev-parse gives you). $CONSENT`,
  prUpdated: String.raw`ArchDev: you just updated pull request #$pr_n. Before you reply, report it with archdev_post_risk_event, event \"pr.updated\", value {\"repository\":\"$pr_repo\",\"number\":$pr_n,\"summary\":\"<what changed>\"}, the project_id you chose, idempotency_key \"$sid-pr-updated-$pr_n-$k\". It needs a fresh sealed whole-PR risk assessment: $RISK_STEPS (resource_type \"pr\", subject source archdev:pr:$pr_repo#$pr_n, full 40-character head and base SHAs). $CONSENT`,
  prClosed: String.raw`ArchDev: you just merged or closed pull request #$pr_n. Before you reply, report it with archdev_post_pr_closed (repository \"$pr_repo\", pull_number $pr_n, head_sha the PR's last head, digest of the whole-PR seal you finalized for its last pr.created or pr.updated report, or read it back with archdev_get_pr_risk, the project_id you chose, idempotency_key \"$sid-pr-closed-$pr_n\"). $CONSENT`,
  stopOwed: String.raw`$2`,
} as const;
