import { HARNESSES, harnessHooks, type Catalog, type Harness } from "./catalog.ts";
import * as opencode from "./harnesses/opencode.ts";

interface Row {
  label: string;
  install: string[];
  notes: string;
  mcp: boolean;
}

/** plugins/README.md: what each plugin contains and how to install it pinned. */
export function installGuide(catalog: Catalog): string {
  const tag = `v${catalog.version}`;
  const repo = "ArchAstro/archdev";
  const rows: Record<Harness, Row> = {
    claude: {
      label: "Claude Code",
      mcp: true,
      install: [
        `claude plugin marketplace add ${repo}#${tag}`,
        `claude plugin install ${catalog.name}@${catalog.name}`,
      ],
      notes: "Sign in to the MCP server with `/mcp`.",
    },
    codex: {
      label: "Codex",
      mcp: true,
      install: [
        `codex plugin marketplace add ${repo} --ref ${tag}`,
        `codex plugin add ${catalog.name}@${catalog.name}`,
      ],
      notes:
        "Codex runs plugin hooks only after you trust them in `/hooks`. Sign in to the MCP server when Codex asks.",
    },
    copilot: {
      label: "GitHub Copilot CLI / VS Code",
      mcp: true,
      install: [
        `copilot plugin marketplace add ${repo}`,
        `copilot plugin install ${catalog.name}@${catalog.name}`,
      ],
      notes:
        'VS Code: add `"' +
        repo +
        '"` to `chat.plugins.marketplaces`. The Copilot cloud agent cannot use OAuth MCP servers.',
    },
    cursor: {
      label: "Cursor",
      mcp: true,
      install: [],
      notes: `Add \`https://github.com/${repo}\` as a team marketplace, or copy \`plugins/cursor\` to \`~/.cursor/plugins/local/${catalog.name}\`.`,
    },
    antigravity: {
      label: "Antigravity",
      mcp: true,
      install: [
        `git clone --depth 1 --branch ${tag} https://github.com/${repo}.git`,
        `agy plugin install ./archdev/plugins/antigravity`,
      ],
      notes: "Authenticate the MCP server in Settings > Customizations.",
    },
    grok: {
      label: "Grok Build",
      mcp: true,
      install: [`grok plugin install ${repo}@${tag}#plugins/grok --trust`],
      notes: "Without `--trust`, Grok asks before running the plugin's hooks.",
    },
    opencode: {
      label: "OpenCode",
      mcp: true,
      install: [],
      notes: `Add \`"plugin": ["${opencode.packageName}@${catalog.version}"]\` to \`opencode.json\`. Sign in with \`opencode mcp auth ${catalog.mcp.name}\`.`,
    },
    pi: {
      label: "Pi",
      mcp: false,
      install: [`pi install git:github.com/${repo}@${tag}`],
      notes: "Pi has no MCP client. Reload Pi after installing.",
    },
  };

  const yes = (value: boolean) => (value ? "yes" : "no");
  const table = HARNESSES.map((harness) => {
    const row = rows[harness];
    return `| ${row.label} | \`plugins/${harness}\` | yes | ${yes(row.mcp)} | ${yes(Boolean(harnessHooks(catalog, harness)))} |`;
  });
  const sections = HARNESSES.map((harness) => {
    const row = rows[harness];
    const entry = catalog.harnesses[harness];
    const unsupported =
      "hooksUnsupported" in entry ? `\n\nNo hooks yet: ${entry.hooksUnsupported}` : "";
    const commands =
      row.install.length > 0 ? `\n\n\`\`\`sh\n${row.install.join("\n")}\n\`\`\`` : "";
    return `### ${row.label}${commands}\n\n${row.notes}${unsupported}`;
  });

  return `# ArchDev plugins

Generated by \`tools/plugin-gen\` from \`catalog/archdev.json\` (version ${catalog.version}). Do not edit files under \`plugins/\` or the marketplace files by hand; change the catalog and run \`npm run build\` in \`tools/plugin-gen\`.

Each plugin bundles the ArchDev skills, the remote MCP server (\`${catalog.mcp.url}\`, OAuth sign-in) and, where the CLI supports the harness, session hooks. The hooks run \`archdev repo hook\` from PATH and do nothing when the CLI is not installed. Hook commands are POSIX shell: they run on macOS and Linux, and on Windows only where the harness runs hooks through Git Bash (Claude Code). Pi's hooks are JavaScript and run everywhere.

The plugin is one of four independent ways to install ArchDev:

1. Plugin: skills, MCP and hooks together (below).
2. Skills only: \`npx skills add ${repo}\`.
3. Hooks only: \`archdev repo hook setup\` from the ArchDev CLI.
4. MCP only: add \`${catalog.mcp.url}\` as a remote MCP server.

Install hooks through either the plugin or \`archdev repo hook setup\` for a given harness, not both: both copies would run and report each event twice.

| Harness | Plugin | Skills | MCP | Hooks |
|---|---|---|---|---|
${table.join("\n")}

Installing from the \`${tag}\` tag pins every file to that release.

${sections.join("\n\n")}
`;
}
