// Generated by tools/plugin-gen from catalog/archdev.json. Do not edit.
// Reload Pi after installation. ArchDev's CLI owns event detection and posting.
const COMMAND = "archdev";
const PREFIX = ["repo","hook"];
const HARNESS = "pi";
const SPEC = "5";
const TOOLS = new RegExp("^(?:bash|edit|write|mcp_call|mcp__.+)$");
const MISSING_CLI = "The ArchDev plugin is installed, but the ArchDev CLI is not on PATH, so session hooks are inactive. Read https://archdev.ai/install.md and ask the user before installing anything.";
const START = "start";

export default function (pi) {
  let bootstrap = "";
  let sessionId;
  let cwd;
  let pending = Promise.resolve();

  async function hook(action, timeout, payload) {
    try {
      const result = await pi.exec(COMMAND, [...PREFIX, action, "--harness", HARNESS, "--spec", SPEC, "--payload", JSON.stringify(payload)], {
        cwd: payload.cwd,
        timeout,
      });
      if (result.code === 127 && action === START) return MISSING_CLI;
      if (result.code !== 0) return "";
      if (action === START) return result.stdout.trim();
      const output = JSON.parse(result.stdout);
      return output?.hookSpecificOutput?.additionalContext || "";
    } catch (error) {
      if (action === START && (error?.code === "ENOENT" || String(error).includes("ENOENT"))) return MISSING_CLI;
      // Monitoring must never prevent a Pi turn or a tool result.
      return "";
    }
  }

  function context(ctx) {
    return { session_id: ctx.sessionManager.getSessionId(), cwd: ctx.cwd };
  }

  pi.on("session_start", async (_event, ctx) => {
    const current = context(ctx);
    sessionId = current.session_id;
    cwd = current.cwd;
    // repo status cannot see a Pi extension from a child process; bind the
    // readiness signal to this session and hook spec instead.
    process.env.ARCHDEV_PI_HOOK_SESSION_ID = sessionId;
    process.env.ARCHDEV_PI_HOOK_SPEC = SPEC;
    pending = Promise.resolve();
    bootstrap = await hook("start", 30000, current);
  });

  pi.on("before_agent_start", async (_event, ctx) => {
    if (ctx.sessionManager.getSessionId() !== sessionId) return;
    await pending;
    const reminder = await hook("prompt", 10000, context(ctx));
    const text = [bootstrap, reminder].filter(Boolean).join("\n\n");
    bootstrap = "";
    if (text) return { message: { customType: "archdev-monitor", content: text, display: false } };
  });

  pi.on("tool_result", async (event, ctx) => {
    if (ctx.sessionManager.getSessionId() !== sessionId || ctx.cwd !== cwd) return;
    if (!TOOLS.test(event.toolName)) return;
    const payload = { ...context(ctx), toolName: event.toolName, toolInput: event.input };
    // Pi may finish parallel tools together; serialize the monitor's state updates.
    const result = pending.then(() => hook("post-tool", 10000, payload));
    pending = result.then(() => undefined);
    const text = await result;
    if (text) return { content: [...event.content, { type: "text", text: "ArchDev monitor: " + text }] };
  });

  pi.on("agent_settled", async (_event, ctx) => {
    if (ctx.sessionManager.getSessionId() !== sessionId) return;
    await pending;
    await hook("stop", 10000, context(ctx));
  });

  pi.on("session_shutdown", async () => {
    await pending;
    if (sessionId && cwd) await hook("end", 10000, { session_id: sessionId, cwd });
    if (process.env.ARCHDEV_PI_HOOK_SESSION_ID === sessionId) {
      delete process.env.ARCHDEV_PI_HOOK_SESSION_ID;
      delete process.env.ARCHDEV_PI_HOOK_SPEC;
    }
  });
}
